import { SideBar } from "@/components/SideBar";
import "./globals.css";
import { Inter } from "next/font/google";

import { SessionProvider } from "@/components/SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/api/auth/[...nextAuth]";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={inter.className}>
      <SessionProvider session={session}>
      </SessionProvider>
        <div className="flex">
          {/*Side Bar*/}
          <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]  ">
            <SideBar />
          </div>
          {/*Client Provider - Notifications*/}

          <div className="flex-1 bg-[#343541]">{children}</div>
        </div>
      </body>
    </html>
  );
}
